apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: omnisci-node
  name: omnisci-node
spec:
  replicas: 2
  template:
    metadata:
      labels:
        name: omnisci-node
    spec:
      containers:
      - image: gcr.io/plotly-hosting/omnisci_db:2
        name: omnisci-node
        imagePullPolicy: Always
        ports:
        - containerPort: 6274

